[publisher]
type = "PUB"
port = 23456

[typestore]
dbfile = "etc/annolityx/annotation-types.json"

[datastore]
type = "elasticsearch"
host = "localhost"
port = 9200
index = "annolityx"
mapping_file = "etc/annolityx/eventannotations-mapping.json"

[http]
port = 9898
webroot = "webroot"
anno_endpoint = "/api/annotations"
types_endpoint = "/api/types"
websocket_endpoint = "/data"
websocket_hostname = "localhost"